# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               couteausuis.se
tagline:             'thoughts'
description:         'projects'
url:                 https://couteausuis.se
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jacob Roy
  url:               https://twitter.com/lejacobroy
  email:             jacob@asteroidlabs.io

# Custom vars
version:             1.0.0
plugins: 
  - jekyll-paginate
collections:
  category:
    output: true
  defaults:
    -
      scope:
        path: ""
        type: category
      values:
        layout: "category"